### PR TITLE
Linter warnings

### PR DESCRIPTION
**Pull request by vazhnov**
* replace tabs with 4 spaces,
* remove trailing spaces,
* fixed a bunch of linter warnings.

### CODE REVIEW

**Comment by vazhnov** [comment]
Just a reminder :)

**Comment by vazhnov** [comment]
@mnalis , could you please take a look?

**Comment by mnalis** [comment]
Hi @vazhnov  and sorry I didn't see this for so long. I'll `wontfix` it however because:

- I no longer use this repository, nor do I intend to maintain the code
- I lack the time to actually verify what the changes do (and I'm not really a python guy)
- I don't like mass-whitespace-changes mixed in with other stuff (it is IMHO is better as two separate PRs - one for whitespace-only changes, one for linter stuff)
- I actually prefer tabs to spaces (and TABs should be 8-chars wide, as $DEITY intended! :smile:) 

You should probably try a PR against upstream https://github.com/erindru/m2t it they are interested (or take maintaining it yourself if you're interested, and upstream is not anymore). I plan to make this repo read-only soon. 

I'm sorry I've let you down after all this time, but I guess some closure is better than no answer :smiling_face_with_tear:

**Comment by vazhnov** [comment]
@mnalis , no problem. Thnank you!

**Pull request closed without merging**
